<?php

namespace App\Custom;

/**
 * Builds the citywide org-chart tree from /get/orgs/chart.
 *
 * WHY THIS IS NOT A STATIC FILE ANY MORE
 * -------------------------------------
 * The tree used to be generated by `php artisan chart:updatejson` into
 * `public/data/orgChart.json`. That had three problems, all found 2026-07-31:
 *
 *  1. It was manual — no cron, no scheduler entry — and the served file was
 *     last written on 2 March 2026, so the chart was five months stale.
 *  2. It wrote to `/var/www/public/data/` INSIDE the `app` container, which
 *     runs from its image; nginx serves the HOST directory. So the output went
 *     somewhere nginx never served, and was destroyed by the next rebuild.
 *  3. A static file cannot offer two views of the same data.
 *
 * Building it per request from the API removes all three. The API already
 * returns everything needed, `Organizations::fetchOrg`-style 503 handling
 * covers an outage, and the two views become two filters over one payload.
 *
 * THE TWO VIEWS
 * -------------
 *   'databook' (default)  Our own editorial chart. Excludes only what WE mark
 *                         off-chart — the 32 orgs that used to hang off the
 *                         `Additional Mayoral Agencies (Not on Chart)` bucket.
 *                         This is the chart the site has always shown.
 *   'nyc'                 Additionally drops every org OTI marks
 *                         `in_org_chart = false`. Narrower and strictly the
 *                         Mayoral org chart as the City publishes it: ~44 fewer
 *                         nodes, losing bodies like the Board of Elections, the
 *                         Campaign Finance Board, the City Planning Commission,
 *                         the pension funds and the public libraries.
 *
 * ⚠ The API applies OUR flag and merely REPORTS OTI's as `oti_in_org_chart`.
 * Conflating the two in one column is what made the second view impossible on
 * the first attempt.
 */
class OrgChart
{
	/**
	 * The org chart's root — `The People of the City of New York`.
	 *
	 * ⚠ 170000000 is NOT a free id. It is the root, hardcoded here and in the
	 * March snapshot the tree was rebuilt from; minting a different id for it
	 * left the generator rootless. Since Phase 3 this is also the tree's map
	 * key, because the map is keyed by org id rather than by `airtable_id`.
	 */
	const ROOT_ID = '170000000';

	/**
	 * Family colours, keyed by the id of the branch head they tint.
	 * Carried over verbatim from ChartUpdateJson so the chart looks unchanged.
	 * ⚠ 170100017 (Chief of Staff) and 170020021 (District Attorneys) are in
	 * here, which is corroboration that the ids restored from the normalizer
	 * core are the original ones.
	 */
	const FAMILY_COLORS = [
		'170011039', '170010056', '170100000', '170100001', '170100007',
		'170100012', '170100016', '170100017', '170100030', '170100035',
		'170100036', '170010010', '170010011', '170010012', '170010013',
		'170010014', '170010103', '170020021', '170011000',
	];

	/** Top-level branch order, as the chart has always presented it. */
	const BRANCH_ORDER = [
		'Elected County Officials', "Mayor's Office", 'Office of the Comptroller',
		'Public Advocate', 'Independent Budget Office', 'City Council',
	];

	/**
	 * @param  array   $orgs  rows from /get/orgs/chart
	 * @param  string  $view  'databook' (default) or 'nyc'
	 * @return array|null     a node tree for sub.orgnode, or null if no root
	 */
	public static function build($orgs, $view = 'databook')
	{
		if (!$orgs)
			return null;

		$mm = [];
		$rootKey = null;

		foreach ($orgs as $org)
		{
			// The NYC view honours OTI's opinion as well as ours. Absent or
			// 'true' both mean keep — only an explicit 'false' excludes, so an
			// org OTI has no opinion about is never silently dropped.
			if ($view === 'nyc' && ($org['oti_in_org_chart'] ?? null) === 'false')
				continue;

			// Phase 3: the tree is keyed by ORG ID and the parent comes from
			// `parent_org_id`, an FK to wegov_orgs(id). It used to be keyed by
			// `airtable_id` with the parent parsed out of `child_of` — a TEXT
			// column holding a JSON-wrapped Airtable id (`["recABC"]`) that was
			// matched to `airtable_id` by string equality. That is why 63 orgs
			// had a parent resolving to nothing, and why every imported org had
			// to be given a synthetic `recOTI…` id just to be referenceable.
			//
			// ⚠ The API guarantees a `parent_org_id` key on every chart row
			// whichever mechanism resolved it (see modules/orgfilter.py
			// parent_id_projection), so there is exactly one code path here.
			$parentKey = ($org['parent_org_id'] ?? null) !== null
				? (string)$org['parent_org_id']
				: null;
			$key = (string)($org['id'] ?? '');
			if ($key === '')
				continue;

			$org['_parent'] = $parentKey;
			$mm[$key] = $org + ['children' => []];

			if ($key === self::ROOT_ID)
				$rootKey = $key;
		}

		// Second pass: attach children only once every node is present, so a
		// parent appearing after its child still gets it.
		foreach ($mm as $key => $node)
		{
			$p = $node['_parent'] ?? null;
			if ($p && isset($mm[$p]))
				$mm[$p]['children'][$node['name']] = $key;
		}

		return $rootKey && isset($mm[$rootKey]) ? self::packnode($mm, $rootKey) : null;
	}

	/**
	 * Render one node and its descendants.
	 *
	 * `Classification` and `Official` nodes render greyed and WITHOUT a link,
	 * because they are not organizations and have no profile page — a grouping
	 * node and a person-role node respectively.
	 */
	protected static function packnode($dd, $key, $familyClass = null)
	{
		$node = $dd[$key];
		$id = (string)($node['id'] ?? '');

		$familyClass = in_array($id, self::FAMILY_COLORS, true)
			? "node_{$id}"
			: ($familyClass ?? null);

		$forceGray = preg_match('~Classification|Official~si', $node['type'] ?? '')
			|| empty($node['datasets_count']);

		// Show NYC's official name where we hold one; the link and the profile
		// stay on the id, and `name` remains the join key (see #173).
		$label = ($node['display_name'] ?? null) ?: ($node['name'] ?? '');

		$rr = [
			'name' => $forceGray
				? "<a>{$label}</a>"
				: "<a href=\"/organization/{$id}\">{$label}</a>",
			'className' => $forceGray ? 'node_def' : ($familyClass ?? 'node_black'),
		];

		if (!empty($node['children']))
		{
			$kids = $node['children'];
			uksort($kids, function ($a, $b) {
				$idx = array_flip(self::BRANCH_ORDER);
				$a = $idx[$a] ?? $a;
				$a = preg_match('~\d~', (string)$a) ? (int)preg_replace('~\D~si', '', $a) : $a;
				$b = $idx[$b] ?? $b;
				$b = preg_match('~\d~', (string)$b) ? (int)preg_replace('~\D~si', '', $b) : $b;
				return $a <=> $b;
			});
			$children = [];
			foreach (array_values($kids) as $childKey)
				$children[] = self::packnode($dd, $childKey, $familyClass);
			$rr['children'] = $children;
		}

		return $rr;
	}

	/** Total nodes in a built tree — used for the view toggle's counts. */
	public static function countNodes($node)
	{
		if (!$node)
			return 0;
		$n = 1;
		foreach ($node['children'] ?? [] as $c)
			$n += self::countNodes($c);
		return $n;
	}
}
